
name: build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Upgrading pip
        run: pip install --upgrade pip

      - name: print environment
        run: pip freeze

      - name: Installing requirements
        run: pip install .

      - name: Installing dev requirements
        run: pip install -r dev_requirements.txt

      - name: Linting with flake8
        run: flake8

      - name: Testing package classes    
        run: pytest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        

